### PR TITLE
Database connection

### PR DESCRIPTION
**Pull request by mscbee**

### CODE REVIEW

**Comment by remusbaciu** [comment]
Few questions :

Do we want to keep the database logic at the API level (current) or service level ? I was thinking that we can just inject the database dependecy in the API but keep the logic in the service.

Do we want to set-up a mocked database and prove functionality through some basic tests ? in that way we can keep the Application class simple. In case we want any bootstrap set-up in the database, we could have a populate database endpoint if required.

Worth adding a readme on how to set-up the database locally ?

**Comment by mscbee** [comment]
> Few questions :
> 
> Do we want to keep the database logic at the API level (current) or service level ? I was thinking that we can just inject the database dependecy in the API but keep the logic in the service.
> 
> Do we want to set-up a mocked database and prove functionality through some basic tests ? in that way we can keep the Application class simple. In case we want any bootstrap set-up in the database, we could have a populate database endpoint if required.
> 
> Worth adding a readme on how to set-up the database locally ?

1. To your first point, you might have noticed that I removed the service level entirely so that everything now lives in the api level. I don't really think we should call that package 'api' either but that's another discussion.  I changed the structure so that it would conform to best practices which in turn enable better ease of use for JPA.

2. Do you mean you want some unit tests to demonstrate that the CRUD functions work? If so, that's possible - I thought we were going to leave testing until slightly later. We can also remove the command line runner that populates the database. I only added it there so that we'd have some data in the store and doing anything with the controller is beyond the scope of this card. What I'll do is create another card with this requirement so that we can keep it in mind.

3. Sure.  I can do that by tomorrow

**Comment by remusbaciu** [comment]
I think when it comes to best practices it's really opinionated, especially when it comes to building APIs.

I believe a strong way to go forward is to keep the logic such as CRUD operations away from the actual API resources and domains. Our domains, such as objects with the data will be constructed at the API level and what happens with that data becomes the responsibility of the service e.g. CRUD.  

Also, i think tests are required to prove functionality and I think TDD is the way to go and to be honest, we don't need  big test coverage, just few tests that prove that whatever we are trying to do works. It also makes development much easier.

I've done some work on the resource level of the API and I will submit a PR to merge it into the your branch.

**Comment by mscbee** [comment]
> I think when it comes to best practices it's really opinionated, especially when it comes to building APIs.
> 
> I believe a strong way to go forward is to keep the logic such as CRUD operations away from the actual API resources and domains. Our domains, such as objects with the data will be constructed at the API level and what happens with that data becomes the responsibility of the service e.g. CRUD.
> 
> But I am happy to keep everything under the api package, and we can talk about renaming as well as long as we are all happy. Might be good to have a chat and define this, but for now we can go forward with what we've got.
> 
> Also, i think tests are required to prove functionality and I think TDD is the way to go and to be honest, we don't need big test coverage, just few tests that prove that whatever we are trying to do works. It also makes development much easier.
> 
> I've done some work on the resource level of the API and I will submit a PR to merge it into the your branch.

So long as it doesn't interfere with using certain dependencies (which the initial structure did) then I'm not overly fussed. Other than that, it's not that deep. 

I've added some tests and some info on accessing the db console on the readme

**Pull request closed without merging**
